apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  labels:
    app:go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:go-app
  template:
    metadata:
      labels:
        app:go-app
    spec:
      containers:
      - name: go-app
        image: mgumaneh2811/go-app:v1
        ports:
        - containerPort: 8080